version:  '3.8'

services:
  nginx:
    build:  ./srcs/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    network:
      - inception

  wordpress:
    build:  ./srcs/wordpress
    environment:
      - WORDPRESS_BD
